[package]
name = "spotifyrs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
querystring = "1.1"
dotenv = "0.15"
getrandom = "0.2"
base64 = "0.13"
sha2 = "0.10"
random-string = "1.0"
reqwest = {version = "0.11", features = ["blocking"]}